version: '3.7'
services:
  php8:
    container_name: "formation-php"
    image: cchampioniocean/php:php8.1-apache
    ports:
      - 81:80
    working_dir: /php-app

  database:
    container_name: "formation-php-mariadb"
    image: mariadb:10.10.2
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
      MARIADB_DATABASE: formation-php
      MARIADB_USER: formation-php
      MARIADB_PASSWORD: formation-php
    ports:
      - 3307:3306

  phpmyadmin:
    container_name: "formation-php-phpmyadmin"
    image: phpmyadmin/phpmyadmin:5.0.4
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 82:80
